# EDA for WiDS competition

Link to competition: https://www.kaggle.com/c/widsdatathon2020/

Description:
The challenge is to create a model that uses data from the first 24 hours of intensive care to predict patient survival. MIT's GOSSIS community initiative, with privacy certification from the Harvard Privacy Lab, has provided a dataset of more than 130,000 hospital Intensive Care Unit (ICU) visits from patients, spanning a one-year timeframe. This data is part of a growing global effort and consortium spanning Argentina, Australia, New Zealand, Sri Lanka, Brazil, and more than 200 hospitals in the United States.

In [1]:
import pandas as pd
import numpy as np

raw_X = pd.read_csv("widsdatathon2020/training_v2.csv")
cols = pd.read_csv("widsdatathon2020/WiDS_Datathon_2020_Dictionary.csv")
cols = cols.drop([12, 187], axis=0) # drop icu_admit_type and pred

In [2]:
np.unique(cols["Data Type"], return_counts=True)

(array(['binary', 'integer', 'numeric', 'string'], dtype=object),
 array([ 16,   7, 152,  11]))

In [3]:
cols[cols["Data Type"] == "integer"]

Category      Variable Name Unit of Measure Data Type  \
0         identifier       encounter_id            None   integer   
1         identifier        hospital_id            None   integer   
2         identifier         patient_id            None   integer   
13       demographic             icu_id            None   integer   
28  APACHE covariate    gcs_eyes_apache            None   integer   
29  APACHE covariate   gcs_motor_apache            None   integer   
31  APACHE covariate  gcs_verbal_apache            None   integer   

                                          Description Example  
0   Unique identifier associated with a patient un...    None  
1        Unique identifier associated with a hospital    None  
2         Unique identifier associated with a patient    None  
13  A unique identifier for the unit to which the ...    None  
28  The eye opening component of the Glasgow Coma ...       4  
29  The motor component of the Glasgow Coma Scale ...       6  
31  The verbal component of the Glasgow Coma Scale...       5

In [4]:
cols["Variable Name"][cols["Category"] == "identifier"]

0    encounter_id
1     hospital_id
2      patient_id
Name: Variable Name, dtype: object

In [5]:
# remove identifier columns and prediction columns
ids = raw_X[cols["Variable Name"][cols["Category"] == "identifier"]]
ids.head()

encounter_id  hospital_id  patient_id
0         66154          118       25312
1        114252           81       59342
2        119783          118       50777
3         79267          118       46918
4         92056           33       34377

In [6]:
X = raw_X[cols["Variable Name"][cols["Category"] != "identifier"]]
X = X.drop("hospital_death", axis=1)
X.head()

age    bmi  elective_surgery  ethnicity gender  height  \
0  68.0  22.73                 0  Caucasian      M   180.3   
1  77.0  27.42                 0  Caucasian      F   160.0   
2  25.0  31.95                 0  Caucasian      F   172.7   
3  81.0  22.64                 1  Caucasian      F   165.1   
4  19.0    NaN                 0  Caucasian      M   188.0   

  hospital_admit_source           icu_admit_source  icu_id icu_stay_type  ...  \
0                 Floor                      Floor      92         admit  ...   
1                 Floor                      Floor      90         admit  ...   
2  Emergency Department       Accident & Emergency      93         admit  ...   
3        Operating Room  Operating Room / Recovery      92         admit  ...   
4                   NaN       Accident & Emergency      91         admit  ...   

  aids  cirrhosis  diabetes_mellitus  hepatic_failure  immunosuppression  \
0  0.0        0.0                1.0              0.0                0.0   
1  0.0        0.0                1.0              0.0                0.0   
2  0.0        0.0                0.0              0.0                0.0   
3  0.0        0.0                0.0              0.0                0.0   
4  0.0        0.0                0.0              0.0                0.0   

   leukemia  lymphoma  solid_tumor_with_metastasis  apache_3j_bodysystem  \
0       0.0       0.0                          0.0                Sepsis   
1       0.0       0.0                          0.0           Respiratory   
2       0.0       0.0                          0.0             Metabolic   
3       0.0       0.0                          0.0        Cardiovascular   
4       0.0       0.0                          0.0                Trauma   

   apache_2_bodysystem  
0       Cardiovascular  
1          Respiratory  
2            Metabolic  
3       Cardiovascular  
4               Trauma  

[5 rows x 182 columns]

In [7]:
y = raw_X["hospital_death"]

In [8]:
# check imbalance of predictions
np.unique(y, return_counts=True)[1]/y.size

array([0.91369817, 0.08630183])

In [9]:
X_scaled = X[cols["Variable Name"][cols["Data Type"] == "numeric"]]
# fill in NA values
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X_scaled = imp.fit_transform(X_scaled)

# PCA on numerical values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_scaled)
X_scaled

array([[0.71232877, 0.73814009, 0.13849782, ..., 0.32089595, 0.55276382,
        0.53299492],
       [0.83561644, 0.39047782, 0.14059582, ..., 0.02107605, 0.73869347,
        0.65482234],
       [0.12328767, 0.60798082, 0.13555836, ..., 0.32089595, 0.50251256,
        0.50761421],
       ...,
       [0.43835616, 0.56516527, 0.13580741, ..., 0.32089595, 0.52763819,
        0.5177665 ],
       [0.63437693, 0.3031341 , 0.13599985, ..., 0.32089595, 0.53768844,
        0.5177665 ],
       [0.90410959, 0.39047782, 0.1356527 , ..., 0.32089595, 0.59798995,
        0.54822335]])

In [10]:
from sklearn.decomposition import PCA
for i in range(2, 10):
    pca = PCA(n_components=i)
    pca.fit(X_scaled)
    print(pca.explained_variance_ratio_)

[0.18949449 0.07655298]
[0.18949449 0.07655298 0.06383089]
[0.18949449 0.07655298 0.06383089 0.05412132]
[0.18949449 0.07655298 0.06383089 0.05412132 0.04341893]
[0.18949449 0.07655298 0.06383089 0.05412132 0.04341897 0.03389489]
[0.18949449 0.07655298 0.06383089 0.05412132 0.04341897 0.03389469
 0.02809618]
[0.18949449 0.07655298 0.06383089 0.05412132 0.04341897 0.03389492
 0.02809557 0.0265101 ]
[0.18949449 0.07655298 0.06383089 0.05412132 0.04341897 0.0338949
 0.02809621 0.02650979 0.02507987]


In [11]:
# jk let's look at lasso
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty="l1", random_state=514).fit(X_scaled, y)


/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [12]:
pd.set_option('display.max_columns', 200)
pd.DataFrame(np.round(clf.coef_, 2), columns=cols["Variable Name"][cols["Data Type"] == "numeric"])

Variable Name   age  height  pre_icu_los_days  weight  albumin_apache  \
0              1.27    0.15              3.36   -0.59            0.11   

Variable Name  bilirubin_apache  bun_apache  creatinine_apache  fio2_apache  \
0                           0.0       -1.14               0.33         0.46   

Variable Name  glucose_apache  heart_rate_apache  hematocrit_apache  \
0                       -0.36              -0.36               0.67   

Variable Name  map_apache  paco2_apache  paco2_for_ph_apache  pao2_apache  \
0                    0.24         -0.09                -0.22        -0.43   

Variable Name  ph_apache  resprate_apache  sodium_apache  temp_apache  \
0                   0.31             0.36          -0.55          0.0   

Variable Name  urineoutput_apache  wbc_apache  d1_diasbp_invasive_max  \
0                           -0.16       -0.25                   -0.09   

Variable Name  d1_diasbp_invasive_min  d1_diasbp_max  d1_diasbp_min  \
0                                0.19          -0.34          -0.11   

Variable Name  d1_diasbp_noninvasive_max  d1_diasbp_noninvasive_min  \
0                                    0.0                        0.0   

Variable Name  d1_heartrate_max  d1_heartrate_min  d1_mbp_invasive_max  \
0                          1.65             -0.44                -0.17   

Variable Name  d1_mbp_invasive_min  d1_mbp_max  d1_mbp_min  \
0                             -0.8       -0.16       -0.81   

Variable Name  d1_mbp_noninvasive_max  d1_mbp_noninvasive_min  \
0                                 0.0                     0.2   

Variable Name  d1_resprate_max  d1_resprate_min  d1_spo2_max  d1_spo2_min  \
0                         -0.2             1.25        -2.52        -2.02   

Variable Name  d1_sysbp_invasive_max  d1_sysbp_invasive_min  d1_sysbp_max  \
0                              -0.13                  -0.51         -0.07   

Variable Name  d1_sysbp_min  d1_sysbp_noninvasive_max  \
0                     -0.94                       0.0   

Variable Name  d1_sysbp_noninvasive_min  d1_temp_max  d1_temp_min  \
0                                 -0.04         0.44        -1.39   

Variable Name  h1_diasbp_invasive_max  h1_diasbp_invasive_min  h1_diasbp_max  \
0                                 0.0                    0.67           0.64   

Variable Name  h1_diasbp_min  h1_diasbp_noninvasive_max  \
0                       0.32                        0.0   

Variable Name  h1_diasbp_noninvasive_min  h1_heartrate_max  h1_heartrate_min  \
0                                    0.0             -0.54              0.43   

Variable Name  h1_mbp_invasive_max  h1_mbp_invasive_min  h1_mbp_max  \
0                             0.46                  0.0       -0.28   

Variable Name  h1_mbp_min  h1_mbp_noninvasive_max  h1_mbp_noninvasive_min  \
0                    0.54                   -0.13                   -1.26   

Variable Name  h1_resprate_max  h1_resprate_min  h1_spo2_max  h1_spo2_min  \
0                         0.12             3.93        -0.17         0.95   

Variable Name  h1_sysbp_invasive_max  h1_sysbp_invasive_min  h1_sysbp_max  \
0                              -0.32                  -0.14         -0.11   

Variable Name  h1_sysbp_min  h1_sysbp_noninvasive_max  \
0                     -0.12                      0.61   

Variable Name  h1_sysbp_noninvasive_min  h1_temp_max  h1_temp_min  \
0                                   0.0        -0.66        -0.27   

Variable Name  d1_albumin_max  d1_albumin_min  d1_bilirubin_max  \
0                         0.0           -0.78              2.11   

Variable Name  d1_bilirubin_min  d1_bun_max  d1_bun_min  d1_calcium_max  \
0                          0.95         0.0        2.18            0.21   

Variable Name  d1_calcium_min  d1_creatinine_max  d1_creatinine_min  \
0                         0.0              -0.55               0.04   

Variable Name  d1_glucose_max  d1_glucose_min  d1_hco3_max  d1_hco3_min  \
0                       -0.07           

In [13]:
from sklearn import metrics
metrics.roc_auc_score(y, clf.predict(X_scaled))


0.6282668522567061

In [15]:
cols["Variable Name"][cols["Data Type"] == "numeric"].to_list()

['age',
 'height',
 'pre_icu_los_days',
 'weight',
 'albumin_apache',
 'bilirubin_apache',
 'bun_apache',
 'creatinine_apache',
 'fio2_apache',
 'glucose_apache',
 'heart_rate_apache',
 'hematocrit_apache',
 'map_apache',
 'paco2_apache',
 'paco2_for_ph_apache',
 'pao2_apache',
 'ph_apache',
 'resprate_apache',
 'sodium_apache',
 'temp_apache',
 'urineoutput_apache',
 'wbc_apache',
 'd1_diasbp_invasive_max',
 'd1_diasbp_invasive_min',
 'd1_diasbp_max',
 'd1_diasbp_min',
 'd1_diasbp_noninvasive_max',
 'd1_diasbp_noninvasive_min',
 'd1_heartrate_max',
 'd1_heartrate_min',
 'd1_mbp_invasive_max',
 'd1_mbp_invasive_min',
 'd1_mbp_max',
 'd1_mbp_min',
 'd1_mbp_noninvasive_max',
 'd1_mbp_noninvasive_min',
 'd1_resprate_max',
 'd1_resprate_min',
 'd1_spo2_max',
 'd1_spo2_min',
 'd1_sysbp_invasive_max',
 'd1_sysbp_invasive_min',
 'd1_sysbp_max',
 'd1_sysbp_min',
 'd1_sysbp_noninvasive_max',
 'd1_sysbp_noninvasive_min',
 'd1_temp_max',
 'd1_temp_min',
 'h1_diasbp_invasive_max',
 'h1_diasbp_inva

In [19]:
coef_vals = pd.DataFrame({"variable": cols["Variable Name"][cols["Data Type"] == "numeric"], "coef": np.round(clf.coef_, 2)[0]})
non_zero_coefs = coef_vals[coef_vals["coef"] != 0]
non_zero_coefs

variable  coef
4                              age  1.27
9                           height  0.15
16                pre_icu_los_days  3.36
18                          weight -0.59
19                  albumin_apache  0.11
25                      bun_apache -1.14
26               creatinine_apache  0.33
27                     fio2_apache  0.46
32                  glucose_apache -0.36
33               heart_rate_apache -0.36
34               hematocrit_apache  0.67
36                      map_apache  0.24
37                    paco2_apache -0.09
38             paco2_for_ph_apache -0.22
39                     pao2_apache -0.43
40                       ph_apache  0.31
41                 resprate_apache  0.36
42                   sodium_apache -0.55
44              urineoutput_apache -0.16
46                      wbc_apache -0.25
47          d1_diasbp_invasive_max -0.09
48          d1_diasbp_invasive_min  0.19
49                   d1_diasbp_max -0.34
50                   d1_diasbp_min -0.11
53                d1_heartrate_max  1.65
54                d1_heartrate_min -0.44
55             d1_mbp_invasive_max -0.17
56             d1_mbp_invasive_min -0.80
57                      d1_mbp_max -0.16
58                      d1_mbp_min -0.81
..                             ...   ...
129                 h1_albumin_max -0.13
130                 h1_albumin_min -0.32
133                     h1_bun_max -0.08
135                 h1_calcium_max -0.58
136                 h1_calcium_min  0.31
138              h1_creatinine_min -0.05
141                    h1_hco3_max  0.30
146              h1_hematocrit_min  0.03
147                     h1_inr_max  0.15
148                     h1_inr_min  0.10
150                 h1_lactate_min -0.63
152               h1_platelets_min  0.01
153               h1_potassium_max -0.11
155                  h1_sodium_max  0.05
157                     h1_wbc_max -0.43
159           d1_arterial_pco2_max  1.17
160           d1_arterial_pco2_min -0.52
161             d1_arterial_ph_max -0.74
162             d1_arterial_ph_min  0.76
163            d1_arterial_po2_max  0.13
164            d1_arterial_po2_min  0.66
165           d1_pao2fio2ratio_max -0.65
166           d1_pao2fio2ratio_min -0.50
168           h1_arterial_pco2_min  0.08
169             h1_arterial_ph_max -0.28
171            h1_arterial_po2_max -1.53
172            h1_arterial_po2_min  1.42
173           h1_pao2fio2ratio_max  0.36
175  apache_4a_hospital_death_prob  5.54
176       apache_4a_icu_death_prob -0.11

[120 rows x 2 columns]

In [23]:
X[non_zero_coefs['variable']]

age  height  pre_icu_los_days  weight  albumin_apache  bun_apache  \
0      68.0   180.3          0.541667    73.9             2.3        31.0   
1      77.0   160.0          0.927778    70.2             NaN         9.0   
2      25.0   172.7          0.000694    95.3             NaN         NaN   
3      81.0   165.1          0.000694    61.7             NaN         NaN   
4      19.0   188.0          0.073611     NaN             NaN         NaN   
5      67.0   190.5          0.000694   100.0             NaN        13.0   
6      59.0   165.1          0.000694   156.6             NaN        18.0   
7      70.0   165.0          0.002083     NaN             NaN        48.0   
8      45.0   170.2          0.009028     NaN             2.7        15.0   
9      50.0   175.3          0.060417    79.0             3.6        10.0   
10     72.0   154.9          0.004861    67.8             NaN         NaN   
11     80.0   160.0          1.271528    70.1             NaN        29.0   
12     48.0   175.3          0.020833     NaN             NaN         NaN   
13     65.0   172.7          1.045139     NaN             2.5        26.0   
14     81.0   172.7          1.376389   113.9             NaN        26.0   
15     78.0   160.0          0.000694     NaN             NaN        34.0   
16     30.0   193.0          0.240972    87.1             NaN        24.0   
17     46.0   167.6          0.000000    72.6             NaN        15.0   
18     65.0   167.6          0.000000    79.8             NaN         NaN   
19     39.0   177.8          5.163889   117.0             NaN         NaN   
20     79.0   170.2          0.893750    82.2             NaN         NaN   
21     80.0   170.2          0.000694   103.3             NaN        18.0   
22     58.0   162.6          0.003472     NaN             NaN        31.0   
23     87.0   180.3          5.046528    71.4             1.6        13.0   
24     60.0   188.0          0.081250   104.3             NaN        12.0   
25     68.0   165.1          0.758333    70.9             1.2        73.0   
26     85.0   152.4          0.000694    55.3             NaN        12.0   
27     79.0   149.9          0.009028    52.6             2.6        15.0   
28      NaN   160.0          1.031944     NaN             3.0        14.0   
29     60.0   180.3          0.000000    86.1             NaN        14.0   
...     ...     ...               ...     ...             ...         ...   
91683  75.0   172.7          0.000000   123.0             NaN         NaN   
91684  19.0   157.5          0.087500    54.2             NaN         NaN   
91685  58.0   173.0          3.331944    75.9             2.4        17.0   
91686  86.0   157.0          0.045139    76.8             NaN        49.0   
91687  71.0   172.7          0.020139    97.5             3.3        16.0   
91688  49.0   182.9          0.132639   106.6             2.6        15.0   
91689   NaN   188.0         -1.735417    86.4             NaN         NaN   
91690  83.0   163.8          0.068750    71.8             4.0        33.0   
91691  59.0   165.0          0.024306    80.0             NaN         NaN   
91692  36.0   162.6          0.011111    54.4             2.4         6.0   
91693   NaN   178.0         -4.731250    58.7             NaN         NaN   
91694  58.0   182.9          0.240278   111.1             4.0        20.0   
91695  49.0   170.2          0.160417    63.0             NaN        10.0   
91696  65.0     NaN          0.069444    95.2             2.4        18.0   
91697  33.0   150.0         11.823611    55.1             NaN         NaN   
91698  47.0   195.0          0.033333   186.0             3.0         9.0   
91699  57.0   188.0          0.232639   119.5             3.3        14.0   
91700  85.0   178.0          0.000000    79.5             NaN        31.0   
91701  21.0   185.4          0.052083    85.5             NaN        21.0   
91702  18.0   172.7          0.000000    60.5             3.1         9.0   
9170

In [25]:
X_scaled = X[non_zero_coefs['variable']]
# fill in NA values
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X_scaled = imp.fit_transform(X_scaled)

# PCA on numerical values
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_scaled)
X_scaled

array([[0.71232877, 0.73814009, 0.13849782, ..., 0.29853242, 0.55276382,
        0.53299492],
       [0.83561644, 0.39047782, 0.14059582, ..., 0.01327434, 0.73869347,
        0.65482234],
       [0.12328767, 0.60798082, 0.13555836, ..., 0.29853242, 0.50251256,
        0.50761421],
       ...,
       [0.43835616, 0.56516527, 0.13580741, ..., 0.29853242, 0.52763819,
        0.5177665 ],
       [0.63437693, 0.3031341 , 0.13599985, ..., 0.29853242, 0.53768844,
        0.5177665 ],
       [0.90410959, 0.39047782, 0.1356527 , ..., 0.29853242, 0.59798995,
        0.54822335]])

In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()
clf.fit(X_scaled, y)
metrics.roc_auc_score(y, clf.predict(X_scaled))

/usr/local/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


0.6602819293642654

In [96]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_scaled, y)
metrics.roc_auc_score(y, gnb.predict(X_scaled))

0.7077989881421823

In [50]:
cols["Data Type"][cols["Variable Name"] == "bmi"] = "numeric"

In [51]:
# let's add in the categoricals
X_cat = raw_X[cols["Variable Name"][cols["Data Type"] == "string"]]
X_cat.head()

ethnicity gender hospital_admit_source           icu_admit_source  \
0  Caucasian      M                 Floor                      Floor   
1  Caucasian      F                 Floor                      Floor   
2  Caucasian      F  Emergency Department       Accident & Emergency   
3  Caucasian      F        Operating Room  Operating Room / Recovery   
4  Caucasian      M                   NaN       Accident & Emergency   

  icu_stay_type      icu_type  apache_2_diagnosis  apache_3j_diagnosis  \
0         admit         CTICU               113.0               502.01   
1         admit  Med-Surg ICU               108.0               203.01   
2         admit  Med-Surg ICU               122.0               703.03   
3         admit         CTICU               203.0              1206.03   
4         admit  Med-Surg ICU               119.0               601.01   

  apache_3j_bodysystem apache_2_bodysystem  
0               Sepsis      Cardiovascular  
1          Respiratory         Respiratory  
2            Metabolic           Metabolic  
3       Cardiovascular      Cardiovascular  
4               Trauma              Trauma

In [88]:
{var: pd.unique(X_cat[var]).size for var in cols["Variable Name"][cols["Data Type"] == "string"]}

{'ethnicity': 7,
 'gender': 3,
 'hospital_admit_source': 16,
 'icu_admit_source': 6,
 'icu_stay_type': 3,
 'icu_type': 8,
 'apache_2_diagnosis': 45,
 'apache_3j_diagnosis': 400,
 'apache_3j_bodysystem': 12,
 'apache_2_bodysystem': 11}

In [84]:
grouped = raw_X.groupby(["ethnicity", "hospital_death"])["hospital_death"].count()
pd.DataFrame(grouped)

hospital_death
ethnicity        hospital_death                
African American 0                         8797
                 1                          750
Asian            0                         1036
                 1                           93
Caucasian        0                        64516
                 1                         6168
Hispanic         0                         3420
                 1                          376
Native American  0                          718
                 1                           70
Other/Unknown    0                         4021
                 1                          353

In [86]:
np.unique([i if type(i)==str else "nan" for i in X_cat["ethnicity"] ], return_counts=True)

(array(['African American', 'Asian', 'Caucasian', 'Hispanic',
        'Native American', 'Other/Unknown', 'nan'], dtype='<U16'),
 array([ 9547,  1129, 70684,  3796,   788,  4374,  1395]))

In [69]:
from bokeh.io import show, output_notebook
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.palettes import Spectral3
output_notebook()
levels, counts =np.unique([i if type(i)==str else "nan" for i in X_cat["ethnicity"] ], return_counts=True)

p = figure(x_range=levels, plot_height=250, title="Fruit Counts",
           toolbar_location=None, tools="")

p.vbar(x=levels, top=counts, width=0.9)

p.xgrid.grid_line_color = None
p.y_range.start = 0

data = {'levels' : levels,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 4, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar_stack(years, x='fruits', width=0.9, color=colors, source=data,
             legend_label=years)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

show(p)

Loading BokehJS ...

In [99]:
pd.get_dummies(raw_X["icu_admit_source"], prefix="icu_admit_source")

icu_admit_source_Accident & Emergency  icu_admit_source_Floor  \
0                                          0                       1   
1                                          0                       1   
2                                          1                       0   
3                                          0                       0   
4                                          1                       0   
5                                          1                       0   
6                                          1                       0   
7                                          1                       0   
8                                          0                       0   
9                                          1                       0   
10                                         0                       0   
11                                         0                       0   
12                                         1                       0   
13                                         0                       0   
14                                         0                       0   
15                                         1                       0   
16                                         1                       0   
17                                         1                       0   
18                                         1                       0   
19                                         0                       0   
20                                         0                       0   
21                                         0                       1   
22                                         0                       0   
23                                         0                       1   
24                                         1                       0   
25                                         0                       1   
26                                         1                       0   
27                                         0                       0   
28                                         0                       0   
29                                         1                       0   
...                                      ...                     ...   
91683                                      1                       0   
91684                                      1                       0   
91685                                      0                       1   
91686                                      1                       0   
91687                                      1                       0   
91688                                      1                       0   
91689                                      1                       0   
91690                                      1                       0   
91691                                      1                       0   
91692                                      1                       0   
91693                                      1                       0   
91694                                      1                       0   
91695                                      1                       0   
91696                                      1                       0   
91697                                      0                       1   
91698                                      0                       0   
91699                                      0                       1   
91700                                      1                       0   
91701                                      1                       0   
91702                                      1                       0   
91703                                      1                       0   
91704                                      1                       0   
91705                                      1                       0   
91706                                      1   

In [100]:
X_add_cat = pd.DataFrame(X_scaled).join(pd.get_dummies(raw_X["ethnicity"], prefix="ethnicity"))
X_add_cat = pd.DataFrame(X_add_cat).join(pd.get_dummies(raw_X["gender"], prefix="gender"))
X_add_cat = pd.DataFrame(X_add_cat).join(pd.get_dummies(raw_X["hospital_admit_source"], prefix="hospital_admit_source"))
X_add_cat = pd.DataFrame(X_add_cat).join(pd.get_dummies(raw_X["icu_admit_source"], prefix="icu_admit_source"))
X_add_cat = pd.DataFrame(X_add_cat).join(pd.get_dummies(raw_X["icu_stay_type"], prefix="icu_stay_type"))
X_add_cat = pd.DataFrame(X_add_cat).join(pd.get_dummies(raw_X["icu_type"], prefix="icu_type"))

In [101]:
gnb = GaussianNB()
gnb.fit(X_add_cat, y)
metrics.roc_auc_score(y, gnb.predict(X_add_cat))

0.7243313655765495